name: Push upon self

on:
    # Triggers the workflow every 00:14 UTC
    schedule:
        - cron: "42 0 * * *"
    push:
        branches:
            [main]

            # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "cron"
    cron:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Runs a single command using the runners shell
            - uses: actions/checkout@v3

            - name: Run a one-line script
              run: ./log.sh
              env:
                  GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NUM: 10
